#STRINGS CONSTANTS

WEEK="Week"

FINANCIAL="Financial"
INFLUENCE="Influence"
INTERNAL="Internal"

ACTION_QUESTION="Do you want to take an action this week? "


AI_TURN="AI's TURN"
PLAYER_TURN=""
PLAYER_POINTS="YOUR POINTS: "
AI_POINTS="AI POINTS: "
PLAYER_RESOURCESS="YOUR RESOURCES: "
AI_RESOURCESS="AI RESOURCES: "

FINAL_SCORE="Final Score for "